databases:
  - name: car_database_app
    databaseName: car_database_app
    user: car_database_app_user

services:
  - type: web
    name: car_rental_ui
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car_database_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false